export interface OfficeShiftSettings {
  officeStartTime: string;     // e.g. "09:00"
  lateThresholdTime: string;   // e.g. "09:20"
  officeEndTime: string;       // e.g. "17:00"
  weeklyOff: string;           // e.g. "Friday"
  workDays: string;            // e.g. "Saturday to Thursday"
  enableGeofence: boolean;
  ipWhitelist: string;
}

export type UserRole = 'super_admin' | 'admin' | 'employee';

export interface UserAccount {
  id: string;
  email: string;
  password?: string;
  name: string;
  role: UserRole;
  employeeId?: string;
  status: 'active' | 'inactive';
  avatar?: string;
  createdAt: string;
}

export interface RegistrationRequest {
  id: string;
  employeeId?: string;
  employeeName: string;
  email: string;
  department: string;
  designation: string;
  dob?: string;
  nidNumber?: string;
  requestedRole: UserRole;
  requestedAt: string;
  status: 'pending' | 'approved' | 'rejected';
  rejectionReason?: string;
  autoGeneratedPassword?: string;
}

export type NavSection =
  | 'dashboard'
  | 'attendance'
  | 'employees'
  | 'leave'
  | 'departments'
  | 'calendar'
  | 'reports'
  | 'analytics'
  | 'holidays'
  | 'settings'
  | 'audit_logs';

export type AttendanceStatus =
  | 'present'
  | 'late'
  | 'grace_period'
  | 'wfh'
  | 'on_leave'
  | 'early_exit'
  | 'absent'
  | 'half_day'
  | 'official_tour';

export type LeaveType = string;

export interface LeavePolicy {
  id: string;
  name: string;
  yearlyQuota: number;
  colorTag: string;
}

export type LeaveStatus = 'approved' | 'pending' | 'rejected';

export type EmploymentType = 'full_time' | 'contract' | 'remote' | 'hybrid';

export interface Employee {
  id: string;
  name: string;
  role: string;
  designation?: string;
  department: string;
  email: string;
  phone: string;
  avatar: string;
  status: 'active' | 'on_leave' | 'inactive';
  employmentType: EmploymentType;
  location: string;
  joinDate: string;
  shift: string;
  leaveUsed?: Record<string, number>;
  leaveBalance: {
    annual: number;
    sick: number;
    casual: number;
    emergency: number;
    unpaid: number;
    maternity: number;
    paternity: number;
    half_day: number;
    [key: string]: number;
  };
  manager: string;
  dob?: string;
  nidNumber?: string;
  address?: string;
  bloodGroup?: string;
}

export interface AttendanceRecord {
  id: string;
  employeeId: string;
  employeeName: string;
  employeeAvatar: string;
  department: string;
  date: string;
  entryTime: string;
  exitTime: string | null;
  workHours: number;
  overtimeHours: number;
  lateMinutes?: number;
  earlyExitMinutes?: number;
  status: AttendanceStatus;
  locationType: 'Office HQ' | 'Remote - Home' | 'Client Site' | 'Geofence App' | 'Official Tour';
  verificationMethod: 'FaceID Biometric' | 'Mobile GPS Geofence' | 'Web Wi-Fi Checkin' | 'RFID Badge' | 'Manual Admin Entry';
  reason?: string;
  notes?: string;
}

export interface LeaveRequest {
  id: string;
  employeeId: string;
  employeeName: string;
  employeeAvatar: string;
  department: string;
  leaveType: LeaveType;
  startDate: string;
  endDate: string;
  totalDays: number;
  reason: string;
  status: LeaveStatus;
  appliedDate: string;
  notes?: string;
  substituteColleague?: string;
  managerComment?: string;
}

export interface Department {
  id: string;
  name: string;
  description?: string;
  headName?: string;
  headAvatar?: string;
  headcount?: number;
  attendanceRate?: number;
  onTimeRate?: number;
  avgHours?: number;
  color?: string;
}

export interface Announcement {
  id: string;
  title: string;
  content: string;
  author: string;
  authorRole: string;
  date: string;
  category: 'policy' | 'event' | 'holiday' | 'general';
  isPinned?: boolean;
}

export interface CompanyHoliday {
  id: string;
  title: string;
  date: string;
  dayOfWeek: string;
  type: 'national' | 'company' | 'religious' | 'corporate' | 'optional';
  appliesTo: string;
  /** 'government' = auto-synced from official BD sources; 'manual' = added by an admin. Defaults to 'manual'. */
  source?: 'government' | 'manual';
  /** Stable sync key for government holidays (one per date). */
  externalId?: string;
}

export interface AuditLog {
  id: string;
  timestamp: string;
  administrator: string;
  actorRole: string;
  action: string;
  target: string;
  oldValue?: string;
  newValue?: string;
  reason?: string;
  ipAddress?: string;
  status: 'success' | 'warning' | 'security_flag';
}

export interface AIInsightData {
  executiveSummary: string;
  healthScore: number;
  keyHighlights: string[];
  burnoutOrLateRisks: {
    title: string;
    severity: 'high' | 'medium' | 'low';
    description: string;
  }[];
  actionableRecommendations: string[];
}

export interface NotificationItem {
  id: string;
  title: string;
  message: string;
  time: string;
  read: boolean;
  type: 'leave' | 'attendance' | 'ai' | 'system';
}

export interface ToastMessage {
  id: string;
  type: 'success' | 'info' | 'warning' | 'error';
  title: string;
  message: string;
}
