import React, { useState } from 'react';
import { UserAccount, Employee, UserRole, RegistrationRequest } from '../../types';
import {
  Users,
  ShieldCheck,
  UserPlus,
  Search,
  Lock,
  Mail,
  CheckCircle2,
  XCircle,
  Trash2,
  Edit2,
  User,
  Shield,
  Key,
  X,
  AlertCircle,
  Clock,
  Send,
  Check,
  Sparkles,
  Eye,
  EyeOff,
} from 'lucide-react';

interface UserAccountsViewProps {
  accounts: UserAccount[];
  employees: Employee[];
  registrationRequests: RegistrationRequest[];
  onCreateAccount: (newAcc: Omit<UserAccount, 'id' | 'createdAt'>) => void;
  onUpdateAccount: (account: UserAccount) => void;
  onDeleteAccount: (accountId: string) => void;
  onAcceptRegistration: (
    request: RegistrationRequest,
    autoGeneratedPassword: string
  ) => void | Promise<{ emailSent: boolean; emailSimulated: boolean } | void>;
  onRejectRegistration: (requestId: string) => void;
  currentUserId: string;
  currentUserRole?: UserRole;
}

export const UserAccountsView: React.FC<UserAccountsViewProps> = ({
  accounts = [],
  employees = [],
  registrationRequests = [],
  onCreateAccount,
  onUpdateAccount,
  onDeleteAccount,
  onAcceptRegistration,
  onRejectRegistration,
  currentUserId,
  currentUserRole = 'super_admin',
}) => {
  const [activeTab, setActiveTab] = useState<'accounts' | 'requests'>('accounts');
  const [searchTerm, setSearchTerm] = useState('');
  const [roleFilter, setRoleFilter] = useState<'all' | UserRole>('all');
  const [isCreateModalOpen, setIsCreateModalOpen] = useState(false);

  // Modal Form State
  const [name, setName] = useState('');
  const [email, setEmail] = useState('');
  const [password, setPassword] = useState('password123');
  const [role, setRole] = useState<UserRole>('employee');
  const [linkedEmployeeId, setLinkedEmployeeId] = useState<string>('');
  const [formError, setFormError] = useState('');

  // Editing state
  const [editingAcc, setEditingAcc] = useState<UserAccount | null>(null);

  // Accept Approval Modal state
  const [selectedRequestToApprove, setSelectedRequestToApprove] = useState<RegistrationRequest | null>(null);
  const [generatedPass, setGeneratedPass] = useState('');
  const [emailSentSuccess, setEmailSentSuccess] = useState(false);
  const [isApproving, setIsApproving] = useState(false);
  const [emailResult, setEmailResult] = useState<{ emailSent: boolean; emailSimulated: boolean } | null>(null);

  const pendingRequests = registrationRequests.filter((r) => r.status === 'pending');

  const filteredAccounts = accounts.filter((acc) => {
    const s = searchTerm.toLowerCase();
    const matchesSearch =
      (acc.name || '').toLowerCase().includes(s) ||
      (acc.email || '').toLowerCase().includes(s) ||
      (acc.id || '').toLowerCase().includes(s);
    const matchesRole = roleFilter === 'all' || acc.role === roleFilter;
    return matchesSearch && matchesRole;
  });

  const superAdminCount = accounts.filter((a) => a.role === 'super_admin').length;
  const adminCount = accounts.filter((a) => a.role === 'admin').length;
  const employeeCount = accounts.filter((a) => a.role === 'employee').length;

  const handleOpenCreate = () => {
    setName('');
    setEmail('');
    setPassword('password123');
    setRole('employee');
    setLinkedEmployeeId(employees[0]?.id || '');
    setFormError('');
    setIsCreateModalOpen(true);
  };

  const handleCreateSubmit = (e: React.FormEvent) => {
    e.preventDefault();
    setFormError('');

    if (!name.trim() || !email.trim() || !password.trim()) {
      setFormError('Please fill in all required fields.');
      return;
    }

    if (accounts.some((a) => (a.email || '').toLowerCase() === email.trim().toLowerCase())) {
      setFormError('An account with this email address already exists.');
      return;
    }

    if (role === 'employee' && !linkedEmployeeId) {
      setFormError('Please select a linked employee profile for Employee role.');
      return;
    }

    const linkedEmp = employees.find((e) => e.id === linkedEmployeeId);

    onCreateAccount({
      name: name.trim(),
      email: email.trim(),
      password: password.trim(),
      role,
      employeeId: role === 'employee' || role === 'admin' ? linkedEmployeeId : undefined,
      status: 'active',
      avatar: linkedEmp?.avatar || 'https://images.unsplash.com/photo-1534528741775-53994a69daeb?auto=format&fit=crop&q=80&w=200',
    });

    setIsCreateModalOpen(false);
  };

  const handleToggleStatus = (acc: UserAccount) => {
    if (acc.id === currentUserId) {
      alert('You cannot deactivate your own logged-in account.');
      return;
    }

    const updated: UserAccount = {
      ...acc,
      status: acc.status === 'active' ? 'inactive' : 'active',
    };
    onUpdateAccount(updated);
  };

  const handleSaveEdit = () => {
    if (editingAcc) {
      onUpdateAccount(editingAcc);
      setEditingAcc(null);
    }
  };

  const handleOpenApproveModal = (req: RegistrationRequest) => {
    const randomNum = Math.floor(1000 + Math.random() * 9000);
    const newPass = `Attendra#${randomNum}`;
    setGeneratedPass(newPass);
    setSelectedRequestToApprove(req);
    setEmailSentSuccess(false);
    setEmailResult(null);
  };

  const handleConfirmApproval = async () => {
    if (!selectedRequestToApprove) return;
    setIsApproving(true);
    try {
      const result = await onAcceptRegistration(selectedRequestToApprove, generatedPass);
      setEmailResult(result || null);
    } catch {
      setEmailResult(null);
    } finally {
      setIsApproving(false);
      setEmailSentSuccess(true);
    }
  };

  return (
    <div className="space-y-6">
      {/* Header */}
      <div className="flex flex-col sm:flex-row sm:items-center justify-between gap-4 p-6 bg-white/90 backdrop-blur-xl border border-slate-200/60 rounded-3xl shadow-[0_8px_30px_rgb(0,0,0,0.04)]">
        <div>
          <div className="flex items-center gap-2">
            <h3 className="text-lg font-extrabold text-slate-900 tracking-tight">
              User Accounts & Registration Governance
            </h3>
            <span className="px-2 py-0.5 text-[10px] font-extrabold uppercase bg-purple-100 text-purple-700 rounded-md">
              Super Admin Only
            </span>
          </div>
          <p className="text-xs text-slate-500 mt-0.5">
            Provision credentials, review employee registration requests, and dispatch auto-generated password emails.
          </p>
        </div>

        <button
          type="button"
          onClick={handleOpenCreate}
          className="flex items-center gap-2 px-4 py-2.5 bg-gradient-to-r from-purple-600 to-indigo-600 hover:opacity-95 text-white font-extrabold text-xs rounded-2xl shadow-md shadow-purple-500/20 transition-all cursor-pointer shrink-0"
        >
          <UserPlus className="w-4 h-4" />
          Create New Account
        </button>
      </div>

      {/* Tabs Navigation */}
      <div className="flex items-center gap-2 border-b border-slate-200 pb-2">
        <button
          type="button"
          onClick={() => setActiveTab('accounts')}
          className={`px-4 py-2 text-xs font-bold rounded-xl transition-all flex items-center gap-2 cursor-pointer ${
            activeTab === 'accounts'
              ? 'bg-purple-600 text-white shadow-xs'
              : 'bg-white text-slate-600 border border-slate-200 hover:bg-slate-50'
          }`}
        >
          <Users className="w-4 h-4" />
          <span>Active User Accounts ({accounts.length})</span>
        </button>

        <button
          type="button"
          onClick={() => setActiveTab('requests')}
          className={`px-4 py-2 text-xs font-bold rounded-xl transition-all flex items-center gap-2 cursor-pointer relative ${
            activeTab === 'requests'
              ? 'bg-purple-600 text-white shadow-xs'
              : 'bg-white text-slate-600 border border-slate-200 hover:bg-slate-50'
          }`}
        >
          <Clock className="w-4 h-4" />
          <span>Pending Employee Requests</span>
          {pendingRequests.length > 0 && (
            <span className="px-1.5 py-0.5 text-[10px] font-black bg-rose-500 text-white rounded-full animate-pulse">
              {pendingRequests.length}
            </span>
          )}
        </button>
      </div>

      {/* Summary KPI Badges */}
      <div className="grid grid-cols-2 md:grid-cols-4 gap-4">
        <div className="p-4 rounded-2xl bg-white border border-slate-200/80 shadow-xs flex items-center gap-3">
          <div className="w-10 h-10 rounded-xl bg-slate-100 text-slate-700 flex items-center justify-center font-bold">
            <Users className="w-5 h-5" />
          </div>
          <div>
            <p className="text-[10px] font-extrabold text-slate-400 uppercase tracking-wider">Total Accounts</p>
            <p className="text-xl font-black text-slate-900">{accounts.length}</p>
          </div>
        </div>

        <div className="p-4 rounded-2xl bg-purple-50/60 border border-purple-200/80 shadow-xs flex items-center gap-3">
          <div className="w-10 h-10 rounded-xl bg-purple-100 text-purple-700 flex items-center justify-center font-bold">
            <ShieldCheck className="w-5 h-5" />
          </div>
          <div>
            <p className="text-[10px] font-extrabold text-purple-600 uppercase tracking-wider">Super Admins</p>
            <p className="text-xl font-black text-purple-900">{superAdminCount}</p>
          </div>
        </div>

        <div className="p-4 rounded-2xl bg-indigo-50/60 border border-indigo-200/80 shadow-xs flex items-center gap-3">
          <div className="w-10 h-10 rounded-xl bg-indigo-100 text-indigo-700 flex items-center justify-center font-bold">
            <Shield className="w-5 h-5" />
          </div>
          <div>
            <p className="text-[10px] font-extrabold text-indigo-600 uppercase tracking-wider">Admins (HR)</p>
            <p className="text-xl font-black text-indigo-900">{adminCount}</p>
          </div>
        </div>

        <div className="p-4 rounded-2xl bg-amber-50/60 border border-amber-200/80 shadow-xs flex items-center gap-3">
          <div className="w-10 h-10 rounded-xl bg-amber-100 text-amber-700 flex items-center justify-center font-bold">
            <Clock className="w-5 h-5" />
          </div>
          <div>
            <p className="text-[10px] font-extrabold text-amber-600 uppercase tracking-wider">Pending Requests</p>
            <p className="text-xl font-black text-amber-900">{pendingRequests.length}</p>
          </div>
        </div>
      </div>

      {/* TAB 1: ACTIVE ACCOUNTS */}
      {activeTab === 'accounts' && (
        <div className="space-y-4">
          {/* Search & Filter Bar */}
          <div className="p-4 bg-white border border-slate-200/80 rounded-2xl shadow-xs flex flex-col sm:flex-row items-center justify-between gap-3">
            <div className="relative flex-1 w-full">
              <Search className="w-4 h-4 text-slate-400 absolute left-3.5 top-1/2 -translate-y-1/2" />
              <input
                type="text"
                placeholder="Search account name or email..."
                value={searchTerm}
                onChange={(e) => setSearchTerm(e.target.value)}
                className="w-full pl-10 pr-4 py-2 text-xs bg-slate-50 border border-slate-200 rounded-xl font-medium text-slate-800 focus:outline-none focus:ring-2 focus:ring-purple-500/20"
              />
            </div>

            <div className="flex items-center gap-2 w-full sm:w-auto">
              <span className="text-xs font-bold text-slate-500 shrink-0">Role:</span>
              <select
                value={roleFilter}
                onChange={(e) => setRoleFilter(e.target.value as any)}
                className="px-3 py-2 text-xs font-bold bg-slate-50 border border-slate-200 rounded-xl text-slate-800 focus:outline-none"
              >
                <option value="all">All Roles ({accounts.length})</option>
                <option value="super_admin">Super Admin ({superAdminCount})</option>
                <option value="admin">Admin ({adminCount})</option>
                <option value="employee">Employee ({employeeCount})</option>
              </select>
            </div>
          </div>

          {/* Account Cards Table */}
          <div className="bg-white border border-slate-200/80 rounded-3xl overflow-hidden shadow-xs">
            <div className="divide-y divide-slate-100">
              {filteredAccounts.map((acc) => {
                const linkedEmp = employees.find((e) => e.id === acc.employeeId);
                const isSelf = acc.id === currentUserId;

                let roleBadge = 'bg-emerald-50 text-emerald-700 border-emerald-200';
                let roleTitle = 'Employee';
                if (acc.role === 'super_admin') {
                  roleBadge = 'bg-purple-50 text-purple-700 border-purple-200';
                  roleTitle = 'Super Admin';
                } else if (acc.role === 'admin') {
                  roleBadge = 'bg-indigo-50 text-indigo-700 border-indigo-200';
                  roleTitle = 'Admin';
                }

                return (
                  <div
                    key={acc.id}
                    className={`p-4 flex flex-col md:flex-row md:items-center justify-between gap-4 transition-colors hover:bg-slate-50/60 ${
                      acc.status === 'inactive' ? 'bg-slate-50/80 opacity-75' : ''
                    }`}
                  >
                    {/* Profile Meta */}
                    <div className="flex items-center gap-3.5 flex-1 min-w-[200px]">
                      <img
                        src={acc.avatar || 'https://images.unsplash.com/photo-1534528741775-53994a69daeb?auto=format&fit=crop&q=80&w=200'}
                        alt={acc.name}
                        className="w-10 h-10 rounded-full object-cover ring-2 ring-slate-200 shrink-0"
                      />
                      <div>
                        <div className="flex items-center gap-2">
                          <h4 className="text-xs font-extrabold text-slate-900">{acc.name}</h4>
                          {isSelf && (
                            <span className="px-1.5 py-0.5 text-[9px] font-black bg-blue-100 text-blue-700 rounded-md">
                              YOU (Current)
                            </span>
                          )}
                        </div>
                        <p className="text-[11px] text-slate-500 font-mono">{acc.email}</p>
                      </div>
                    </div>

                    {/* Role & Linked Employee */}
                    <div className="flex flex-wrap items-center gap-3 md:w-1/2">
                      <div className="shrink-0">
                        <span className={`px-2.5 py-1 text-[10px] font-extrabold uppercase rounded-full border ${roleBadge}`}>
                          {roleTitle}
                        </span>
                      </div>

                      <div className="text-xs text-slate-600 truncate flex-1 min-w-[140px]">
                        <span className="text-[10px] font-bold text-slate-400 block">LINKED RECORD:</span>
                        {linkedEmp ? (
                          <span className="font-bold text-slate-800">{linkedEmp.name} ({linkedEmp.id})</span>
                        ) : (
                          <span className="italic text-slate-400">None</span>
                        )}
                      </div>

                      <div className="shrink-0">
                        {acc.status === 'active' ? (
                          <span className="flex items-center gap-1 text-[11px] font-bold text-emerald-600 bg-emerald-50 border border-emerald-200 px-2.5 py-0.5 rounded-full">
                            <CheckCircle2 className="w-3.5 h-3.5" />
                            Active
                          </span>
                        ) : (
                          <span className="flex items-center gap-1 text-[11px] font-bold text-rose-600 bg-rose-50 border border-rose-200 px-2.5 py-0.5 rounded-full">
                            <XCircle className="w-3.5 h-3.5" />
                            Deactivated
                          </span>
                        )}
                      </div>
                    </div>

                    {/* Actions */}
                    <div className="flex items-center gap-2 pt-2 md:pt-0 border-t md:border-t-0 border-slate-100 justify-end shrink-0">
                      <button
                        type="button"
                        onClick={() => setEditingAcc(acc)}
                        className="px-3 py-1.5 text-xs font-bold text-slate-700 bg-slate-100 hover:bg-slate-200 rounded-xl transition-colors cursor-pointer flex items-center gap-1"
                      >
                        <Edit2 className="w-3.5 h-3.5 text-slate-500" />
                        Edit
                      </button>

                      <button
                        type="button"
                        onClick={() => handleToggleStatus(acc)}
                        disabled={isSelf}
                        className={`px-3 py-1.5 text-xs font-bold rounded-xl transition-colors cursor-pointer ${
                          acc.status === 'active'
                            ? 'text-amber-700 bg-amber-50 hover:bg-amber-100 border border-amber-200'
                            : 'text-emerald-700 bg-emerald-50 hover:bg-emerald-100 border border-emerald-200'
                        } ${isSelf ? 'opacity-50 cursor-not-allowed' : ''}`}
                      >
                        {acc.status === 'active' ? 'Deactivate' : 'Reactivate'}
                      </button>

                      {!isSelf && (
                        <button
                          type="button"
                          onClick={() => {
                            if (confirm(`Are you sure you want to delete account for ${acc.name}?`)) {
                              onDeleteAccount(acc.id);
                            }
                          }}
                          className="p-1.5 text-slate-400 hover:text-rose-600 hover:bg-rose-50 rounded-xl transition-colors cursor-pointer"
                          title="Delete User Account"
                        >
                          <Trash2 className="w-4 h-4" />
                        </button>
                      )}
                    </div>
                  </div>
                );
              })}
            </div>
          </div>
        </div>
      )}

      {/* TAB 2: PENDING REGISTRATION REQUESTS */}
      {activeTab === 'requests' && (() => {
        const pendingRequests = registrationRequests.filter((r) => r.status === 'pending');
        return (
          <div className="space-y-4">
            <div className="p-4 bg-amber-50/80 border border-amber-200 rounded-2xl text-xs text-amber-900 flex items-start gap-3">
              <Sparkles className="w-5 h-5 text-amber-600 shrink-0 mt-0.5" />
              <div>
                <p className="font-extrabold text-amber-950">Pending Employee Account Access Desk</p>
                <p className="text-[11px] text-amber-800 mt-0.5">
                  When you click <strong>"Approve & Activate Account"</strong>, a random strong password will be generated, the account will be activated in Active Users, and the employee profile will become visible in the Employee Directory.
                </p>
              </div>
            </div>

            {pendingRequests.length === 0 ? (
              <div className="p-8 text-center bg-white border border-slate-200 rounded-3xl space-y-2">
                <CheckCircle2 className="w-8 h-8 text-emerald-500 mx-auto" />
                <p className="text-xs font-extrabold text-slate-800">No Pending Registration Requests</p>
                <p className="text-[11px] text-slate-400">All employee account requests have been processed.</p>
              </div>
            ) : (
              <div className="bg-white border border-slate-200/80 rounded-3xl overflow-hidden shadow-xs divide-y divide-slate-100">
                {pendingRequests.map((req) => {
                  return (
                    <div key={req.id} className="p-4 flex flex-col md:flex-row md:items-center justify-between gap-4">
                      <div className="flex items-center gap-3.5">
                        <div className="w-10 h-10 rounded-2xl bg-indigo-50 border border-indigo-100 text-indigo-700 flex items-center justify-center font-bold text-xs shrink-0 uppercase">
                          {req.employeeName ? req.employeeName.substring(0, 2) : 'REQ'}
                        </div>
                        <div>
                          <div className="flex items-center gap-2">
                            <h4 className="text-xs font-extrabold text-slate-900">{req.employeeName}</h4>
                            <span className="px-2 py-0.5 text-[9px] font-extrabold uppercase bg-amber-100 text-amber-800 rounded-md">
                              {req.status}
                            </span>
                          </div>
                          <p className="text-[11px] text-slate-500 font-mono">{req.email}</p>
                          <div className="flex items-center gap-2 text-[10px] text-slate-500 mt-0.5">
                            <span className="px-1.5 py-0.5 rounded-md bg-slate-100 font-bold text-slate-700">{req.department || 'Engineering'}</span>
                            <span className="text-slate-300">•</span>
                            <span className="font-semibold text-slate-600">{req.designation || 'Staff'}</span>
                            {req.employeeId && (
                              <>
                                <span className="text-slate-300">•</span>
                                <span className="font-mono text-purple-700 font-bold">{req.employeeId}</span>
                              </>
                            )}
                          </div>
                          <p className="text-[10px] text-slate-400 mt-0.5">Requested: {req.requestedAt ? new Date(req.requestedAt).toLocaleString() : 'Recently'}</p>
                        </div>
                      </div>

                      <div className="flex items-center gap-3">
                        <button
                          type="button"
                          onClick={() => handleOpenApproveModal(req)}
                          className="px-3.5 py-2 bg-emerald-600 hover:bg-emerald-700 text-white font-extrabold text-xs rounded-xl shadow-xs flex items-center gap-1.5 cursor-pointer"
                        >
                          <Send className="w-3.5 h-3.5" />
                          Approve & Generate Password
                        </button>

                        <button
                          type="button"
                          onClick={() => onRejectRegistration(req.id)}
                          className="px-3 py-2 bg-rose-50 hover:bg-rose-100 text-rose-700 font-bold text-xs rounded-xl border border-rose-200 cursor-pointer"
                        >
                          Reject
                        </button>
                      </div>
                    </div>
                  );
                })}
              </div>
            )}
          </div>
        );
      })()}

      {/* Auto-Generated Email Dispatch Preview Modal */}
      {selectedRequestToApprove && (
        <div className="fixed inset-0 z-50 flex items-center justify-center p-4 bg-slate-900/60 backdrop-blur-md animate-fade-in">
          <div className="bg-white border border-slate-200 rounded-3xl p-6 w-full max-w-lg shadow-2xl space-y-4 relative">
            <button
              onClick={() => setSelectedRequestToApprove(null)}
              className="absolute right-4 top-4 p-2 text-slate-400 hover:text-slate-600 rounded-full"
            >
              <X className="w-4 h-4" />
            </button>

            <div className="flex items-center gap-3">
              <div className="w-10 h-10 rounded-2xl bg-emerald-50 border border-emerald-100 text-emerald-600 flex items-center justify-center shrink-0">
                <Mail className="w-5 h-5" />
              </div>
              <div>
                <h3 className="text-sm font-extrabold text-slate-900">Email Gateway Dispatch Preview</h3>
                <p className="text-[11px] text-slate-500">Auto-Generated Password Access Delivery</p>
              </div>
            </div>

            {!emailSentSuccess ? (
              <div className="space-y-4">
                <div className="bg-slate-900 text-slate-100 p-4 rounded-2xl text-xs space-y-2.5 font-sans border border-slate-800">
                  <div className="flex items-center justify-between border-b border-slate-800 pb-2 text-[11px]">
                    <span className="text-slate-400 font-mono">FROM:</span>
                    <span className="font-bold text-purple-400">Attendra Portal Security Desk</span>
                  </div>
                  <div className="flex items-center justify-between border-b border-slate-800 pb-2 text-[11px]">
                    <span className="text-slate-400 font-mono">TO:</span>
                    <span className="font-bold text-emerald-400">{selectedRequestToApprove.email}</span>
                  </div>
                  <div className="flex items-center justify-between border-b border-slate-800 pb-2 text-[11px]">
                    <span className="text-slate-400 font-mono">SUBJECT:</span>
                    <span className="font-bold text-white">Your Attendra Employee Portal Account Approved</span>
                  </div>

                  <div className="pt-2 text-slate-200 text-xs space-y-2 leading-relaxed">
                    <p>Dear <strong>{selectedRequestToApprove.employeeName}</strong>,</p>
                    <p>
                      Your account registration request for <strong>{selectedRequestToApprove.designation || 'Employee'}</strong> in <strong>{selectedRequestToApprove.department || 'Engineering'}</strong> department has been approved by Super Admin.
                    </p>
                    <div className="p-3 bg-slate-800/90 rounded-xl border border-slate-700/80 space-y-1 font-mono text-[11px]">
                      <p className="text-slate-400">Login Email: <span className="text-white font-bold">{selectedRequestToApprove.email}</span></p>
                      <p className="text-slate-400">Auto-Generated Password: <span className="text-emerald-400 font-bold">•••••••• (Dispatched via Email)</span></p>
                    </div>
                    <p className="text-[11px] text-slate-400">
                      You can now use these credentials to sign in to the portal at any time.
                    </p>
                  </div>
                </div>

                <div className="flex items-center justify-end gap-2 pt-2">
                  <button
                    type="button"
                    onClick={() => setSelectedRequestToApprove(null)}
                    className="px-4 py-2 text-xs font-bold text-slate-600 hover:bg-slate-100 rounded-xl"
                  >
                    Cancel
                  </button>
                  <button
                    type="button"
                    onClick={handleConfirmApproval}
                    disabled={isApproving}
                    className="px-5 py-2 text-xs font-extrabold text-white bg-emerald-600 hover:bg-emerald-700 disabled:opacity-60 disabled:cursor-not-allowed rounded-xl shadow-xs flex items-center gap-1.5 cursor-pointer"
                  >
                    <Send className="w-3.5 h-3.5" />
                    {isApproving ? 'Sending…' : 'Confirm Approval & Send Email'}
                  </button>
                </div>
              </div>
            ) : (
              <div className="space-y-4 text-center py-4 animate-fade-in">
                <div className="w-12 h-12 rounded-full bg-emerald-50 border border-emerald-200 text-emerald-600 mx-auto flex items-center justify-center">
                  <Check className="w-6 h-6" />
                </div>
                <h4 className="text-sm font-extrabold text-slate-900">Registration Approved</h4>
                {emailResult?.emailSent ? (
                  <div className="p-3.5 bg-emerald-50 border border-emerald-200 rounded-2xl text-xs text-emerald-900 font-medium leading-relaxed text-left">
                    Account approved. Temporary password has been emailed to <strong className="font-mono font-bold text-emerald-950">{selectedRequestToApprove.email}</strong>.
                  </div>
                ) : (
                  <div className="p-3.5 bg-amber-50 border border-amber-200 rounded-2xl text-xs text-amber-900 font-medium leading-relaxed text-left">
                    Account approved and activated, but the welcome email <strong>could not be confirmed as delivered</strong> to <strong className="font-mono font-bold text-amber-950">{selectedRequestToApprove.email}</strong>.
                    {emailResult?.emailSimulated && ' (Email sending isn\u2019t configured on this server yet.)'}
                    {' '}Please share the temporary password below manually:
                    <div className="mt-2 font-mono text-sm font-bold text-amber-950 bg-white/70 border border-amber-200 rounded-lg px-2 py-1 inline-block">
                      {generatedPass}
                    </div>
                  </div>
                )}
                <button
                  type="button"
                  onClick={() => setSelectedRequestToApprove(null)}
                  className="w-full py-2.5 bg-slate-900 text-white font-bold text-xs rounded-xl shadow-xs cursor-pointer"
                >
                  Close & Done
                </button>
              </div>
            )}
          </div>
        </div>
      )}

      {/* Create Account Modal */}
      {isCreateModalOpen && (
        <div className="fixed inset-0 z-50 flex items-center justify-center p-4 bg-slate-900/60 backdrop-blur-md animate-fade-in">
          <div className="bg-white border border-slate-200 rounded-3xl p-6 w-full max-w-lg shadow-2xl space-y-4 relative">
            <button
              onClick={() => setIsCreateModalOpen(false)}
              className="absolute right-4 top-4 p-2 text-slate-400 hover:text-slate-600 rounded-full"
            >
              <X className="w-4 h-4" />
            </button>

            <div className="flex items-center gap-3">
              <div className="w-10 h-10 rounded-2xl bg-purple-50 border border-purple-100 flex items-center justify-center text-purple-600 shrink-0">
                <UserPlus className="w-5 h-5" />
              </div>
              <div>
                <h3 className="text-sm font-extrabold text-slate-900">Provision User Account</h3>
                <p className="text-[11px] text-slate-500">Create login credentials and link employee record</p>
              </div>
            </div>

            <form onSubmit={handleCreateSubmit} className="space-y-3.5">
              {formError && (
                <div className="p-3 bg-rose-50 border border-rose-200 rounded-2xl flex items-center gap-2 text-xs text-rose-800 font-semibold">
                  <AlertCircle className="w-4 h-4 text-rose-600 shrink-0" />
                  <span>{formError}</span>
                </div>
              )}

              <div>
                <label className="text-xs font-bold text-slate-700 block mb-1">Full Name *</label>
                <input
                  type="text"
                  value={name}
                  onChange={(e) => setName(e.target.value)}
                  placeholder="e.g. Sarah Jenkins"
                  className="w-full px-3.5 py-2 text-xs bg-slate-50 border border-slate-200 rounded-xl font-bold text-slate-800 focus:outline-none focus:ring-2 focus:ring-purple-500/20"
                  required
                />
              </div>

              <div className="grid grid-cols-2 gap-3">
                <div>
                  <label className="text-xs font-bold text-slate-700 block mb-1">Work Email *</label>
                  <input
                    type="email"
                    value={email}
                    onChange={(e) => setEmail(e.target.value)}
                    placeholder="user@attendra.io"
                    className="w-full px-3.5 py-2 text-xs bg-slate-50 border border-slate-200 rounded-xl font-bold text-slate-800 focus:outline-none focus:ring-2 focus:ring-purple-500/20"
                    required
                  />
                </div>
                <div>
                  <label className="text-xs font-bold text-slate-700 block mb-1">Password *</label>
                  <input
                    type="password"
                    value={password}
                    onChange={(e) => setPassword(e.target.value)}
                    placeholder="••••••••"
                    className="w-full px-3.5 py-2 text-xs bg-slate-50 border border-slate-200 rounded-xl font-bold text-slate-800 focus:outline-none focus:ring-2 focus:ring-purple-500/20"
                    required
                  />
                </div>
              </div>

              <div>
                <label className="text-xs font-bold text-slate-700 block mb-1">Assign System Access Role *</label>
                <select
                  value={role}
                  onChange={(e) => setRole(e.target.value as UserRole)}
                  className="w-full px-3.5 py-2 text-xs font-bold bg-slate-50 border border-slate-200 rounded-xl text-slate-800 focus:outline-none focus:ring-2 focus:ring-purple-500/20"
                >
                  <option value="employee">Employee (Restricted to Own Attendance & Leave)</option>
                  <option value="admin">Admin (Manage All Attendance & Leaves, Restricted Settings)</option>
                  <option value="super_admin">Super Admin (Full Governance, Policy Quotas & Account Setup)</option>
                </select>
              </div>

              <div>
                <label className="text-xs font-bold text-slate-700 block mb-1">
                  Link to Employee Profile {role === 'employee' ? '*' : '(Optional)'}
                </label>
                <select
                  value={linkedEmployeeId}
                  onChange={(e) => {
                    setLinkedEmployeeId(e.target.value);
                    const selectedEmp = employees.find((emp) => emp.id === e.target.value);
                    if (selectedEmp && !name) {
                      setName(selectedEmp.name);
                    }
                  }}
                  className="w-full px-3.5 py-2 text-xs font-bold bg-slate-50 border border-slate-200 rounded-xl text-slate-800 focus:outline-none focus:ring-2 focus:ring-purple-500/20"
                >
                  <option value="">-- No Linked Employee Record --</option>
                  {employees.map((emp) => (
                    <option key={emp.id} value={emp.id}>
                      {emp.name} ({emp.id}) — {emp.department}
                    </option>
                  ))}
                </select>
              </div>

              <div className="flex items-center justify-end gap-2 pt-2">
                <button
                  type="button"
                  onClick={() => setIsCreateModalOpen(false)}
                  className="px-4 py-2 text-xs font-bold text-slate-600 hover:bg-slate-100 rounded-xl"
                >
                  Cancel
                </button>
                <button
                  type="submit"
                  className="px-5 py-2 text-xs font-extrabold text-white bg-purple-600 hover:bg-purple-700 rounded-xl shadow-xs"
                >
                  Create & Enable Account
                </button>
              </div>
            </form>
          </div>
        </div>
      )}

      {/* Edit Account Modal */}
      {editingAcc && (
        <div className="fixed inset-0 z-50 flex items-center justify-center p-4 bg-slate-900/60 backdrop-blur-md animate-fade-in">
          <div className="bg-white border border-slate-200 rounded-3xl p-6 w-full max-w-md shadow-2xl space-y-4 relative">
            <button
              onClick={() => setEditingAcc(null)}
              className="absolute right-4 top-4 p-2 text-slate-400 hover:text-slate-600 rounded-full"
            >
              <X className="w-4 h-4" />
            </button>

            <h3 className="text-sm font-extrabold text-slate-900">Edit User Account: {editingAcc.name}</h3>

            <div className="space-y-3">
              <div>
                <label className="text-xs font-bold text-slate-700 block mb-1">Display Name</label>
                <input
                  type="text"
                  value={editingAcc.name}
                  onChange={(e) => setEditingAcc({ ...editingAcc, name: e.target.value })}
                  className="w-full px-3.5 py-2 text-xs bg-slate-50 border border-slate-200 rounded-xl font-bold text-slate-800"
                />
              </div>

              <div>
                <label className="text-xs font-bold text-slate-700 block mb-1">Work Email Address</label>
                <input
                  type="email"
                  value={editingAcc.email}
                  onChange={(e) => setEditingAcc({ ...editingAcc, email: e.target.value })}
                  className="w-full px-3.5 py-2 text-xs bg-slate-50 border border-slate-200 rounded-xl font-bold text-slate-800"
                  required
                />
              </div>

              <div>
                <label className="text-xs font-bold text-slate-700 block mb-1">Role</label>
                <select
                  value={editingAcc.role}
                  onChange={(e) => setEditingAcc({ ...editingAcc, role: e.target.value as UserRole })}
                  className="w-full px-3.5 py-2 text-xs font-bold bg-slate-50 border border-slate-200 rounded-xl text-slate-800"
                >
                  <option value="super_admin">Super Admin</option>
                  <option value="admin">Admin</option>
                  <option value="employee">Employee</option>
                </select>
              </div>

              <div>
                <label className="text-xs font-bold text-slate-700 block mb-1">Linked Employee</label>
                <select
                  value={editingAcc.employeeId || ''}
                  onChange={(e) => setEditingAcc({ ...editingAcc, employeeId: e.target.value })}
                  className="w-full px-3.5 py-2 text-xs font-bold bg-slate-50 border border-slate-200 rounded-xl text-slate-800"
                >
                  <option value="">-- Unlinked --</option>
                  {employees.map((emp) => (
                    <option key={emp.id} value={emp.id}>
                      {emp.name} ({emp.id})
                    </option>
                  ))}
                </select>
              </div>

              <div className="flex items-center justify-end gap-2 pt-2">
                <button
                  type="button"
                  onClick={() => setEditingAcc(null)}
                  className="px-4 py-2 text-xs font-bold text-slate-600 hover:bg-slate-100 rounded-xl"
                >
                  Cancel
                </button>
                <button
                  type="button"
                  onClick={handleSaveEdit}
                  className="px-5 py-2 text-xs font-extrabold text-white bg-blue-600 hover:bg-blue-700 rounded-xl shadow-xs"
                >
                  Save Account Changes
                </button>
              </div>
            </div>
          </div>
        </div>
      )}
    </div>
  );
};
